/* Package-owned capabilities retain documentation and source attribution. */
const FC={area:'all',query:'',selected:null,tab:'overview',bound:false};
const featureTabs=[['overview','作用与使用'],['implementation','实现与注释'],['relations','引用与协作'],['config','配置与限制'],['evidence','来源与验证']];
function featureMatches(f){const p=packageByName.get(f.id);return (FC.area==='all'||f.area===FC.area)&&(!FC.query||(f.title+' '+p.name+' '+plain(p.summary)+' '+(f.tools?.names||[]).join(' ')+' '+D.meta.groups[p.group]).toLowerCase().includes(FC.query.toLowerCase()));}
function renderFeatures(){
 const target=decodeURIComponent(location.hash.split('/').slice(1).join('/'));if(D.features.items.some(f=>f.id===target))FC.selected=target;
 if(!FC.selected)FC.selected=D.features.items.find(f=>f.id==='@deepseek-ai/dsh-tool-fs')?.id||D.features.items[0].id;
 $('#main').innerHTML=heading('CAPABILITY DIRECTORY · SOURCE EVIDENCE','功能清单 · 统览项目能做什么','按大模块认识功能，再查看使用方式、实现依据与协作关系。所有资料都在当前 HTML 内离线读取。')+`<div class="fc-stats"><div><b>${D.features.items.length}</b><span>包级功能条目</span></div><div><b>${D.matrix.areas.length}</b><span>大模块</span></div><div><b>${D.features.toolCount}</b><span>目录中的工具名称</span></div><div><b>10+</b><span>功能阅读维度</span></div></div><div class="fc-intro"><b>新手读法：</b>先看“作用与使用”，再查“引用与协作”，最后打开源码核对实现。基础库、界面插件、工具和启动组合均保留类型，不把每个包都当成独立可用的产品功能。<details><summary>收录范围与完整性</summary><p>${esc(D.features.scope)} 覆盖当前快照全部 ${D.packages.length} 个项目包；具体操作来自工具目录和各包说明。动态外部 MCP 工具、个人配置与 vendor 内部实现不在此清单内。测试文件仅列位置，列出不代表本次运行了这些测试。</p></details></div><div class="fc-search"><input id="fc-query" class="input" type="search" value="${esc(FC.query)}" placeholder="搜索功能、中文用途、包名或工具，例如：文件、read_image、会话…" aria-label="搜索功能清单"><button class="btn" data-fc-reset>全部模块</button><span id="fc-count" class="muted small"></span></div><div class="fc-layout"><nav id="fc-tree" class="fc-tree" aria-label="大模块与功能菜单"></nav><article id="fc-detail" class="fc-detail"></article></div>`;
 paintFeatureTree();paintFeatureDetail();
 if(!FC.bound){FC.bound=true;document.addEventListener('click',e=>{if(currentPage!=='features')return;const b=e.target.closest('[data-feature],[data-fc-area],[data-fc-tab],[data-fc-reset]');if(!b)return;if(b.hasAttribute('data-feature')){FC.selected=b.dataset.feature;FC.tab='overview';history.replaceState(null,'','#features/'+encodeURIComponent(FC.selected));paintFeatureTree();paintFeatureDetail();if(innerWidth<900)$('#fc-detail').scrollIntoView({behavior:'smooth',block:'start'});}if(b.hasAttribute('data-fc-area')){FC.area=b.dataset.fcArea;paintFeatureTree();}if(b.hasAttribute('data-fc-tab')){FC.tab=b.dataset.fcTab;paintFeatureDetail();}if(b.hasAttribute('data-fc-reset')){FC.area='all';FC.query='';$('#fc-query').value='';paintFeatureTree();}});document.addEventListener('input',e=>{if(e.target.id==='fc-query'){FC.query=e.target.value;paintFeatureTree();}});}
}
function paintFeatureTree(){
 const list=D.features.items.filter(featureMatches);$('#fc-count').textContent=`${list.length} / ${D.features.items.length} 条`;
 $('#fc-tree').innerHTML=D.matrix.areas.filter(a=>FC.area==='all'||FC.area===a.id).map(a=>{const items=list.filter(f=>f.area===a.id);return `<details class="fc-module" ${FC.query||FC.area===a.id||items.some(f=>f.id===FC.selected)?'open':''}><summary>${esc(a.title)}<span>${items.length}</span></summary><button class="fc-filter" data-fc-area="${a.id}">只看此模块 →</button>${items.map(f=>`<button class="fc-item ${FC.selected===f.id?'active':''}" data-feature="${esc(f.id)}" ${FC.selected===f.id?'aria-current="true"':''}><strong>${esc(f.title)}</strong><small>${esc(packageByName.get(f.id).short)}</small></button>`).join('')||'<p class="small muted">无匹配功能</p>'}</details>`;}).join('');
}
function featureDocs(f,p,regex){const sections=f.sections.filter(s=>regex.test(s.title));return sections.length?sections.map(s=>`<section class="fc-section"><h3>${esc(s.title)}</h3><div class="markdown">${markdown(s.text,p.readme)}</div><div class="fc-attribution">来源：${sourceButton(p.readme,'包的中文说明 ↗',s.line)}</div></section>`).join(''):'<p class="fc-empty">该包说明未单列此章节；请查看完整说明及源码，不能据此推断没有相关行为。</p>';}
function featureLinks(names){return names.length?names.map(name=>D.features.items.some(f=>f.id===name)?`<button class="fc-chip" data-feature="${esc(name)}">${esc(packageByName.get(name).short)} ↗</button>`:badge(name)).join(' '):'<span class="muted">清单未记录</span>';}
function paintFeatureDetail(){
 const f=D.features.items.find(f=>f.id===FC.selected),p=packageByName.get(f.id),area=D.matrix.areas.find(a=>a.id===f.area);
 let body='';
 if(FC.tab==='overview')body=`<section class="fc-section"><h3>这个功能有什么用？</h3><div class="markdown">${markdown(p.summary,p.readme)}</div><div class="fc-attribution">提取自包说明的概述，保留原文含义。</div></section>${f.tools?`<section class="fc-section"><h3>具体工具操作 · ${f.tools.names.length}</h3><div class="fc-chips">${f.tools.names.map(n=>badge(n,true)).join(' ')}</div><p>依赖：${esc(f.tools.dependencies)}</p><p>写入与影响：${esc(f.tools.effects)}</p><p>别名：${esc(f.tools.aliases)} · 部署说明：${esc(f.tools.notes)}</p>${sourceButton('docs/tool-catalog.zh.md','查看工具参数与完整 Schema ↗',f.tools.line)}</section>`:''}${featureDocs(f,p,/使用|用法|快速|安装|消费者|消费入口/)}`;
 if(FC.tab==='implementation')body=featureDocs(f,p,/实现|设计|架构/)+`<section class="fc-section"><h3>实现入口</h3>${p.entries.map(x=>`<p>${sourceButton(x,x)}</p>`).join('')||'<p>本清单未识别到约定的 index.ts 入口；请查完整包说明。</p>'}<h3>入口文件的 JSDoc 注释 · ${f.comments.length}</h3><p class="muted">以下是源码原始注释，不自动翻译或推断实现；完整逻辑请打开源码。只提取已识别入口文件的 JSDoc。</p>${f.comments.map(c=>`<details class="fc-comment"><summary>${esc(c.text.split('\n')[0]||'源码注释')}</summary><pre>${esc(c.text)}</pre>${sourceButton(c.file,c.file+':'+c.line,c.line)}</details>`).join('')}</section>`;
 if(FC.tab==='relations'){
 const services=D.matrix.services.filter(s=>[...s.definition,...s.providers,...s.consumers].includes(p.name)),events=D.matrix.events.filter(s=>[...s.dispatchers,...s.listeners].includes(p.name));
 body=`<section class="fc-section"><h3>它引用哪些包？</h3><p>来自 dependencies 与 peerDependencies；不表示直接调用顺序。</p><div class="fc-chips">${featureLinks(p.deps)}</div><h3>哪些功能引用它？ · ${f.incoming.length}</h3><div class="fc-chips">${featureLinks(f.incoming)}</div></section><section class="fc-section"><h3>服务分工 · ${services.length}</h3>${services.map(s=>`<details class="fc-comment"><summary>${esc(s.name)} · ${[s.definition.includes(p.name)?'定义':'',s.providers.includes(p.name)?'提供':'',s.consumers.includes(p.name)?'使用':''].filter(Boolean).join(' / ')}</summary><p>定义方 ${featureLinks(s.definition)}</p><p>提供方 ${featureLinks(s.providers)}</p><p>使用方 ${featureLinks(s.consumers)}</p>${sourceButton(s.file,'服务目录依据 ↗',s.line)}</details>`).join('')||'<p>目录未记录服务角色。</p>'}<h3>事件关系 · ${events.length}</h3>${events.map(e=>`<details class="fc-comment"><summary>${esc(e.name)} · ${esc(e.mode)}</summary><p>派发 ${featureLinks(e.dispatchers)}</p><p>监听 ${featureLinks(e.listeners)}</p>${sourceButton(e.file,'事件目录依据 ↗',e.line)}</details>`).join('')||'<p>目录未记录事件关系。</p>'}</section><section class="fc-section"><h3>哪些启动组合引用它？</h3><p>静态配置引用不等于实际启用；包含预设内延迟条目和显式禁用项。</p>${D.matrix.profiles.filter(pr=>pr.rows.some(r=>r.package===p.name)).map(pr=>`<p>${badge(pr.id,true)} ${pr.rows.filter(r=>r.package===p.name).length} 条引用 · ${sourceButton(pr.file,'模板依据 ↗')}</p>`).join('')||'<p>已扫描模板未直接命名引用。</p>'}${btn('打开启动对比','data-nav="matrix"')}</section>`;
 }
 if(FC.tab==='config')body=`<section class="fc-section"><h3>配置声明</h3>${f.config?`<div class="markdown">${markdown(f.config.text,'docs/config-catalog.zh.md')}</div>${sourceButton('docs/config-catalog.zh.md','完整配置目录 ↗',f.config.line)}`:'<p>配置目录未收录该包条目，请查包说明；这不等于不需要配置。</p>'}</section>${featureDocs(f,p,/限制|模型体验|失败|恢复/)}`;
 if(FC.tab==='evidence')body=`<section class="fc-section"><h3>来源与版本</h3><dl class="fc-facts"><dt>功能拥有者</dt><dd>${esc(p.name)}</dd><dt>目录</dt><dd>${esc(p.path)}</dd><dt>所属细分模块</dt><dd>${esc(D.meta.groups[p.group]||p.group)}</dd><dt>包类型</dt><dd>${esc(p.role)}</dd><dt>源码基线</dt><dd>${esc(D.meta.head)}</dd><dt>生成时间</dt><dd>${esc(D.meta.generated)}</dd><dt>提取方式</dt><dd>中文 README、包清单、服务/事件目录与入口 JSDoc 的静态汇总；未运行产品验证其每项行为。</dd></dl><div class="actions">${sourceButton(p.readme,'中文功能说明')}${sourceButton(p.path+'/package.json','包元数据')}</div><h3>关联测试位置 · ${f.tests.length}</h3><p>路径来自受 Git 跟踪文件；不表示已执行或已通过。测试文件未内置时仅显示路径。</p><div class="fc-paths">${f.tests.map(t=>D.files[t]?sourceButton(t,t):`<code>${esc(t)}</code>`).join('')||'<p>包内未匹配测试文件，测试可能由其他目录负责。</p>'}</div><h3>源码文件 · ${p.sources.length}</h3><details><summary>展开文件列表</summary><div class="fc-paths">${p.sources.map(x=>sourceButton(x,x)).join('')}</div></details></section>`;
 $('#fc-detail').innerHTML=`<div class="fc-detail-head"><div class="eyebrow">${esc(area.title)} / ${esc(D.meta.groups[p.group]||p.group)}</div><h2>${esc(f.title)}</h2><p class="fc-package">${esc(p.name)}</p>${badge(p.role,true)} ${badge(p.group==='experimental'?'实验能力':'项目源码')}<div class="actions">${btn('完整中文说明',`data-package="${esc(p.name)}"`)}${p.entries[0]?sourceButton(p.entries[0],'直接读源码 ↗'):''}</div></div><div class="fc-tabs" role="tablist" aria-label="功能详情维度">${featureTabs.map(([id,title])=>`<button role="tab" aria-selected="${FC.tab===id}" data-fc-tab="${id}" class="${FC.tab===id?'active':''}">${title}</button>`).join('')}</div><div class="fc-body enter">${body}</div>`;
}
