/** Localized presentation labels. */
export const zh = {
  'welcome.eyebrow': 'YOUR DAY, REIMAGINED WITH AI',
  'welcome.title': '上午好。\n今天，我们一起完成什么？',
  'welcome.lead': '从一个想法，到一次行动。你的 AI 工作伙伴，随时就绪。',
  'welcome.tip': '当前任务只使用本工作区的资料',
  'stage.aiNotice': '内容由 AI 生成，请核实重要信息',
  'stage.demoOnly': '本地交互演示，未连接业务系统',
  'stage.newSession': '新会话',
  'view.label': '阅读视图',
  'view.chat': '对话摘要',
  'pending.updated': '待回答请求状态已更新，请以当前会话为准。',
} as const

/** Localized presentation labels. */
export const en = {
  'welcome.eyebrow': 'YOUR DAY, REIMAGINED WITH AI',
  'welcome.title': 'Good morning.\nWhat shall we finish together today?',
  'welcome.lead': 'From an idea to an action. Your AI work partner is ready.',
  'welcome.tip': 'This task only uses the current workspace material',
  'stage.aiNotice': 'Content is generated by AI; verify anything important',
  'stage.demoOnly': 'Local interaction demo, no business system connected',
  'stage.newSession': 'New session',
  'view.label': 'Reading view',
  'view.chat': 'Conversation',
  'pending.updated': 'The pending request status has changed. Follow the current session state.',
} as const
