/* Standalone UX prototype. All business results are local demonstrations. */
'use strict';
const $ = (q, root = document) => root.querySelector(q);
const esc = (s = '') => String(s).replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const paths = {
  spark:'M12 2 14.8 9.2 22 12 14.8 14.8 12 22 9.2 14.8 2 12 9.2 9.2Z',
  panel:'M9 3v18M4 3h16a1 1 0 0 1 1 1v16a1 1 0 0 1-1 1H4a1 1 0 0 1-1-1V4a1 1 0 0 1 1-1Z',
  right:'M15 3v18M4 3h16a1 1 0 0 1 1 1v16a1 1 0 0 1-1 1H4a1 1 0 0 1-1-1V4a1 1 0 0 1 1-1Z',
  grid:'M3 3h7v7H3ZM14 3h7v7h-7ZM3 14h7v7H3ZM14 14h7v7h-7Z',
  plus:'M12 5v14M5 12h14', close:'m6 6 12 12M6 18 18 6', chevron:'m8 10 4 4 4-4', left:'m14 6-6 6 6 6', next:'m9 6 6 6-6 6', arrow:'M5 12h14m-6-6 6 6-6 6', up:'M12 19V5m-6 6 6-6 6 6',
  chat:'M21 11a8 8 0 0 1-8 8H6l-4 3V11a9 9 0 0 1 19 0Z', pin:'m9 3 6 0-1 7 4 4H6l4-4ZM12 14v7',
  more:'M5 12h.01M12 12h.01M19 12h.01', folder:'M3 7V4h6l3 3h9v13H3ZM3 7h18', file:'M14 2H5v20h14V7Zm0 0v6h5M8 12h8M8 16h6',
  upload:'M12 16V3m-5 5 5-5 5 5M4 16v5h16v-5', attach:'m8 12 6-6a3 3 0 0 1 4 4L9 19a5 5 0 0 1-7-7L13 1',
  agent:'M8 3h8v4H8ZM4 7h16v13H4ZM8 12h.01M16 12h.01M8 16h8M1 11v5M23 11v5',
  plugin:'M8 3v5M16 3v5M5 8h14v4a7 7 0 0 1-7 7v3M5 8v4a7 7 0 0 0 7 7',
  book:'M12 5C9 2 4 3 2 4v16c3-2 7-2 10 0 3-2 7-2 10 0V4c-3-1-7-2-10 1Zm0 0v15',
  skill:'m13 2-9 12h7l-1 8 10-13h-7Z', mobile:'M7 2h10a2 2 0 0 1 2 2v16a2 2 0 0 1-2 2H7a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2ZM10 18h4',
  settings:'M9 3h6l1 4 4 1v7l-4 1-1 5H9l-1-5-4-1V8l4-1ZM12 9a3 3 0 1 0 0 6 3 3 0 0 0 0-6Z',
  user:'M12 3a4 4 0 1 0 0 8 4 4 0 0 0 0-8ZM4 21v-3a8 6 0 0 1 16 0v3', lock:'M6 10h12v11H6ZM8 10V6a4 4 0 0 1 8 0v4M12 14v3',
  eye:'M2 12q10-14 20 0-10 14-20 0ZM12 9a3 3 0 1 0 0 6 3 3 0 0 0 0-6Z', eyeOff:'m3 3 18 18M9 5q8-3 13 7-2 3-4 4M6 6q-2 2-4 6 6 9 13 6',
  shield:'m12 2 9 4v6c0 5-9 10-9 10S3 17 3 12V6Zm-5 9 3 3 7-7', check:'m5 12 4 4L19 6', clock:'M12 8v5l3 2M12 2a10 10 0 1 0 0 20 10 10 0 0 0 0-20Z',
  calendar:'M4 5h16v16H4ZM4 10h16M8 2v6M16 2v6M8 14h2M14 14h2M8 18h2', todo:'M9 6h12M9 12h12M9 18h12M2 5l2 2 3-4M2 12h3M2 18h3',
  chart:'M4 3v17h17M7 14l4-5 4 3 6-8', video:'M3 5h13v14H3ZM16 10l6-4v12l-6-4Z', box:'m12 2 10 5v10l-10 5L2 17V7Zm0 10v10M2 7l10 5 10-5M7 4.5l10 5',
  mic:'M8 5a4 4 0 0 1 8 0v7a4 4 0 0 1-8 0ZM4 10v2a8 8 0 0 0 16 0v-2M12 20v3', copy:'M8 8h13v13H8ZM16 8V3H3v13h5',
  refresh:'M20 8a9 9 0 1 0 0 9M20 3v5h-5', thumb:'M7 10h-4v11h4Zm0 0 5-8c3 0 3 3 1 7h7l1 2-3 10H7Z', download:'M12 3v13m-5-5 5 5 5-5M4 17v4h16v-4',
  trash:'M3 6h18M9 6V3h6v3M5 6l1 15h12l1-15M10 10v7M14 10v7', edit:'m3 16 13-13 5 5L8 21H3Zm11-11 5 5', logout:'M9 3H3v18h6M9 12h12m-5-5 5 5-5 5',
  search:'M10 2a8 8 0 1 0 0 16 8 8 0 0 0 0-16Zm6 14 6 6', globe:'M12 2a10 10 0 1 0 0 20 10 10 0 0 0 0-20Zm0 0q-9 10 0 20 9-10 0-20M2 12h20', stop:'M6 6h12v12H6Z', info:'M12 11v6M12 7h.01M12 2a10 10 0 1 0 0 20 10 10 0 0 0 0-20Z'
};
const icon = name => `<svg class="icon" aria-hidden="true" viewBox="0 0 24 24"><path d="${paths[name] || paths.spark}"/></svg>`;
const ib = (name, label, action, extra = '') => `<button type="button" class="icon-button" aria-label="${esc(label)}" title="${esc(label)}" data-action="${action}" ${extra}>${icon(name)}</button>`;
const brand = () => `<div class="brand"><span class="logo-mark">${icon('spark')}</span><div><strong>奇术</strong><small>QISHU · AI WORKSPACE</small></div></div>`;
const uid = () => window.crypto?.randomUUID?.() || `${Date.now()}-${Math.random().toString(36).slice(2)}`;
const STORE = 'yuvi-prototype-v1';
const BASE_DATE = '2026-09-13';
const models = ['DeepSeek V3.2', 'DeepSeek R1', 'Qwen3（演示）'];
const categories = {
 agents:{title:'数字智能体',desc:'把专业能力交给专属助手，由奇术为你协调。',items:[['设备监测智能体','持续关注设备状态，协助分析异常趋势。','chart'],['安全检查智能体','整理检查发现，跟进隐患整改与复查。','shield'],['视觉分析智能体','对照现场视频，辅助识别异常行为。','video'],['具身控制智能体','编排机器人与无人机任务，执行前需确认。','agent']]},
 plugins:{title:'插件中心',desc:'管理工作台可使用的扩展能力。此处开关只影响演示原型。',items:[['浏览器接管','让智能体在授权范围内协助浏览器操作。','globe'],['报告导出','将分析结果整理为可下载的文档。','download'],['消息推送','将任务进度发送至已连接的消息终端。','mobile'],['现场视频接入','将摄像头画面作为任务分析材料。','video']]},
 rag:{title:'RAG 知识库',desc:'让回答有据可依，管理当前工作区的参考资料。',items:[['安全生产制度库','安全规范、检查制度与岗位职责 · 28 份资料','shield'],['设备维护手册','设备操作、维护与检修知识 · 16 份资料','book'],['SOP 作业规范','岗位标准流程与作业检查清单 · 12 份资料','todo'],['历史隐患案例','整改措施与复查记录 · 36 份资料','file']]},
 skills:{title:'Skill 中心',desc:'把常用工作方法保存为可复用的技能。',items:[['生成巡检计划','按区域与设备，生成可确认的巡检安排。','calendar'],['异常原因分析','关联运行趋势、检修记录与现场证据。','chart'],['编写安全周报','汇总检查记录与整改情况，生成报告草稿。','file'],['SOP 执行复核','逐步核对标准步骤，标记需要人工复核的片段。','check']]},
 apps:{title:'应用中心',desc:'所有能力，从一个入口出发。选择应用即可在对话中开始任务。',items:[['设备监测','关注实时运行状态与异常趋势。','chart'],['安全检查','检查、整改、复查，完整跟进每一项隐患。','shield'],['全景 VR','从全景视角了解现场空间与设备。','globe'],['SOP 检测','将现场作业与标准操作步骤对齐。','todo'],['AI 算法检测','查看模型检测结果与部署状态。','box'],['企业驾驶舱','汇总你所关注的全域生产情况。','grid']]},
 terminals:{title:'移动终端',desc:'将工作台连接到日常沟通工具，在熟悉的地方发起任务。',items:[['飞书','连接后，可在飞书接收提醒并发起对话。','mobile'],['企业微信','连接企业微信，协同处理现场检查任务。','chat'],['钉钉','通过钉钉接收待办、日程与任务进度。','calendar']]}
};
function seedWorkspace(name, alternate = false) {
 const titles = alternate ? ['仓库消防设施检查','第三季度整改汇总'] : ['二车间设备异常排查','本周安全生产报告','制定明日巡检计划','SOP 作业流程复核','分析 3 号泵运行趋势'];
 return {name, current:null, sessions:titles.map((title,i)=>({id:uid(),title,pinned:i===0,messages:[{role:'user',text:title},{role:'assistant',text:'已整理当前工作区的相关资料。你可以查看下面的示例结果，或者继续告诉我想深入了解的内容。',kind:i===1?'report':'analysis'}]})),todos:[{id:uid(),text:alternate?'复核仓库消防设施':'复核 3 号泵温度异常',date:BASE_DATE,done:false},{id:uid(),text:'确认明日巡检人员安排',date:'2026-09-14',done:false},{id:uid(),text:'检查报告归档',date:BASE_DATE,done:true}],events:[{id:uid(),title:'安全生产例会',date:BASE_DATE,time:'09:30',place:'一号会议室'},{id:uid(),title:'二车间现场巡检',date:BASE_DATE,time:'14:00',place:alternate?'东侧仓库':'二车间'}],files:[{id:uid(),name:'安全生产管理制度.pdf',size:'2.4 MB',type:'PDF',sample:true},{id:uid(),name:'本周设备运行数据.xlsx',size:'856 KB',type:'XLSX',sample:true},{id:uid(),name:'车间巡检记录.docx',size:'1.2 MB',type:'DOCX',sample:true}],project:alternate?'仓库安全管理':'安全生产日常管理'};
}
function initial() {return {version:1,workspace:'w1',workspaces:{w1:seedWorkspace('华东工厂 · 主工作区'),w2:seedWorkspace('东侧仓库 · 协作空间',true)},settings:{theme:'light',compact:false,enterSend:true,model:models[0]},enabled:{},recent:['设备监测','安全检查','SOP 检测','全景 VR'],rememberUser:null};}
let state;
try { const data=JSON.parse(localStorage.getItem(STORE)); state=data?.version===1&&data.workspaces?.[data.workspace]?data:initial(); } catch {state=initial();}
let user;
try{user=JSON.parse(sessionStorage.getItem('yuvi-user')) || state.rememberUser;}catch{user=state.rememberUser;}
const ui={left:innerWidth>700,right:innerWidth>960,tab:'workspace',mode:'chat',draft:'',attachments:[],thinking:false,pending:null,calendar:'2026-09',day:BASE_DATE,fileTarget:'chat'};
const viewportMode=()=>innerWidth<=700?'mobile':innerWidth<=960?'tablet':'desktop';
let layoutMode=viewportMode();
const panelPreferences={desktop:{left:true,right:true},tablet:{left:true,right:false}};
function syncPanelDom(){
 const mobile=viewportMode()==='mobile';
 if(mobile&&ui.left&&ui.right)ui.left=false;
 for(const [key,selector] of [['left','.sidebar'],['right','.right-panel']]){
  const panel=$(selector),toggle=$(`[data-action="toggle-${key}"]`);
  if(!panel||!toggle)continue;
  if(!ui[key]&&panel.contains(document.activeElement))toggle.focus();
  panel.classList.toggle('hidden',!ui[key]);panel.toggleAttribute('inert',!ui[key]);
  toggle.setAttribute('aria-expanded',String(ui[key]));
  const label=(ui[key]?'收起':'展开')+(key==='left'?'左侧导航':'右侧面板');
  toggle.setAttribute('aria-label',label);toggle.title=label;
 }
 $('.mobile-overlay')?.classList.toggle('active',innerWidth<=960&&(ui.right||(mobile&&ui.left)));
}
let viewportFrame;
function updateViewport(){
 cancelAnimationFrame(viewportFrame);
 viewportFrame=requestAnimationFrame(()=>{
  const viewport=window.visualViewport;
  const height=viewport&&viewport.scale===1?viewport.height:innerHeight;
  document.documentElement.style.setProperty('--viewport-height',`${Math.round(height)}px`);
  const mode=viewportMode();
  if(mode!==layoutMode){
   if(layoutMode!=='mobile')panelPreferences[layoutMode]={left:ui.left,right:ui.right};
   const next=mode==='mobile'?{left:false,right:false}:panelPreferences[mode];
   ui.left=next.left;ui.right=mode==='tablet'?false:next.right;layoutMode=mode;
  }
  syncPanelDom();
 });
}
window.addEventListener('resize',updateViewport);
window.visualViewport?.addEventListener('resize',updateViewport);
updateViewport();
let timer,toastTimer;
const ws=()=>state.workspaces[state.workspace];
const current=()=>ws().sessions.find(s=>s.id===ws().current);
function save(){try{localStorage.setItem(STORE,JSON.stringify(state));}catch{toast('本机存储不可用；本次更改仅保留到关闭页面。');}}
function toast(msg){$('#toast').textContent=msg;$('#toast').classList.add('visible');clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('#toast').classList.remove('visible'),3200);}
function openModal(title,body,wide=false){const d=$('#modal');d.classList.toggle('wide',wide);d.innerHTML=`<div class="modal-head"><h2 id="modal-title">${esc(title)}</h2>${ib('close','关闭弹窗','close-modal')}</div><div class="modal-body">${body}</div>`;if(!d.open)d.showModal();}
function closeModal(){$('#modal').close();}
function buttons(primary,action){return `<div class="modal-actions"><button class="btn" type="button" data-action="close-modal">取消</button><button class="btn primary" type="submit" ${action?`data-action="${action}"`:''}>${primary}</button></div>`;}
function renderLogin(){
 document.body.className='';
 $('#root').innerHTML=`<main class="login"><section class="login-story">${brand()}<div class="story-copy"><div class="eyebrow">YOUR INTELLIGENCE. EVERYWHERE.</div><h1>一个人，一句话。<br><span>看见全域，掌控全局。</span></h1><p>让 AI 连接设备、现场与每一个工作瞬间。<br>从感知到行动，让复杂的事，简单发生。</p></div><div class="factory-visual"><object type="image/svg+xml" data="factory.svg" aria-label="操作员通过 AI 中枢连接整座智能工厂">AI 智能工厂示意图</object></div><div class="story-footer"><span><i class="dot"></i>感知 · 协同 · 行动</span><span>BUILT FOR AN INTELLIGENT WORLD</span></div></section><section class="login-panel"><div class="login-top"><span class="tag">交互原型</span><button class="text-button" data-action="help">使用帮助 ${icon('next')}</button></div><div class="login-form-wrap"><div class="mobile-brand">${brand()}</div><div class="form-kicker">WELCOME TO QISHU</div><h2>欢迎回到奇术</h2><p>登录你的 AI 工作台，让工作从对话开始。</p><form id="login-form" novalidate><div class="field"><label for="username">用户名</label><div class="input-wrap">${icon('user')}<input id="username" name="username" autocomplete="username" placeholder="请输入用户名" required aria-describedby="login-error"></div></div><div class="field"><label for="password">密码</label><div class="input-wrap">${icon('lock')}<input id="password" name="password" type="password" autocomplete="current-password" placeholder="请输入密码" required aria-describedby="login-error">${ib('eye','显示密码','toggle-password')}</div></div><div class="login-options"><label class="check-label"><input id="remember" type="checkbox">自动登录</label><button type="button" class="text-button" data-action="password-help">忘记密码？</button></div><button type="submit" class="btn primary block login-submit"><span>登 录</span>${icon('arrow')}</button><div id="login-error" class="form-error" role="alert"></div></form><div class="demo-login"><button class="text-button" data-action="fill-demo">${icon('spark')}填入演示账号 ${icon('arrow')}</button><br>用户名 admin · 密码 Demo@2026<br>仅用于本地体验，请勿输入真实账号密码。</div></div><div class="login-bottom">${icon('shield')} 安全连接，从信任开始<br>© 2026 奇术 QISHU · AI 安全生产智能体平台</div></section></main>`;
}
function sidebar(){const w=ws();const section=(title,sessions)=>`<div class="section-heading"><span>${title}</span><span>${sessions.length?String(sessions.length).padStart(2,'0'):''}</span></div>${sessions.map(s=>`<div class="session-row ${w.current===s.id?'active':''}"><button class="session-link" data-action="select-session" data-id="${s.id}">${icon(s.pinned?'pin':'chat')}<span>${esc(s.title)}</span></button><button class="icon-button session-more" aria-label="管理会话 ${esc(s.title)}" data-action="session-menu" data-id="${s.id}">${icon('more')}</button></div>`).join('')}`;
 return `<aside class="sidebar ${ui.left?'':'hidden'}" aria-label="主导航" ${ui.left?'':'inert'}><button class="workspace-picker" data-action="workspaces"><span class="workspace-avatar">${icon('box')}</span><span class="workspace-name">${esc(w.name)}</span>${icon('chevron')}</button><button class="new-chat" data-action="new-chat">${icon('plus')}<span>新建会话</span><small class="shortcut">Ctrl K</small></button><div class="session-scroll">${section('置顶会话',w.sessions.filter(s=>s.pinned&&!s.archived))}${section('最近会话',w.sessions.filter(s=>!s.pinned&&!s.archived))}${!w.sessions.some(s=>!s.archived)?'<p class="empty">从一个问题开始<br>你的会话会保存在这里</p>':''}</div><div class="sidebar-tools"><div class="section-heading"><span>最近使用</span><button class="text-button" data-action="catalog" data-category="apps" aria-label="查看全部应用">···</button></div><div class="recent-apps">${state.recent.slice(0,4).map(name=>{const app=categories.apps.items.find(i=>i[0]===name);return `<button class="recent-app" aria-label="打开${esc(name)}" title="${esc(name)}" data-action="app-detail" data-name="${esc(name)}" data-category="apps">${icon(app?.[2]||'grid')}</button>`;}).join('')}</div><div class="tool-links">${[['agents','agent','数字智能体'],['plugins','plugin','插件中心'],['rag','book','RAG 知识库'],['skills','skill','Skill 中心'],['apps','grid','应用中心'],['terminals','mobile','移动终端']].map(([key,ic,label])=>`<button class="tool-link" data-action="catalog" data-category="${key}">${icon(ic)}${label}</button>`).join('')}</div></div><div class="sidebar-bottom"><button class="profile-trigger" data-action="profile"><span class="avatar">王</span><span><strong>王工 <span class="muted">⌄</span></strong><small>安全管理员</small></span></button>${ib('settings','设置','settings')}</div></aside>`;
}
function composer(){return `<div class="composer-shell"><div class="composer"><div class="attachments">${ui.attachments.map(f=>`<div class="attachment">${icon('file')}<span>${esc(f.name)}</span>${ib('close','移除附件 '+f.name,'remove-attachment',`data-id="${f.id}"`)}</div>`).join('')}</div><label for="prompt" class="sr-only">会话任务输入框</label><textarea id="prompt" placeholder="描述你的任务，或上传文件，让奇术帮你一起完成…">${esc(ui.draft)}</textarea><div class="composer-bottom"><div class="composer-left">${ib('plus','上传文件','upload', 'data-target="chat"')}<span class="composer-divider"></span><label class="model-select"><span class="sr-only">选择模型</span><select id="model">${models.map(m=>`<option ${m===state.settings.model?'selected':''}>${esc(m)}</option>`).join('')}</select>${icon('chevron')}</label><button class="thinking-chip ${ui.thinking?'active':''}" data-action="thinking" aria-pressed="${ui.thinking}">${icon('spark')}深度思考</button></div><div class="composer-right">${ib('mic','语音输入演示','voice')}<button class="send ${ui.pending?'is-stop':''}" aria-label="${ui.pending?'停止生成':'发送消息'}" data-action="${ui.pending?'stop':'send'}">${icon(ui.pending?'stop':'up')}</button></div></div></div><div class="suggestions">${[['chart','看看今天的设备状态'],['shield','生成安全检查计划'],['file','整理本周安全报告']].map(([ic,t])=>`<button class="suggestion" data-action="suggestion" data-text="${t}">${icon(ic)}${t}</button>`).join('')}</div></div>`;}
function assistantResult(kind){const report=kind==='report';return `<div class="result-card"><div class="result-header">${icon(report?'file':'chart')}<span>${report?'安全生产周报 · 草稿':'一厂设备运行概览'}</span><span class="tag">演示数据</span></div><div class="result-grid"><div><small>${report?'覆盖检查':'已连接设备'}</small><strong>${report?'6':'128'}<em>${report?'次':'台'}</em></strong></div><div><small>${report?'待整改隐患':'正常运行'}</small><strong>${report?'3':'126'}<em>${report?'项':'台'}</em></strong></div><div><small>需要关注</small><strong>2<em>项</em></strong></div></div><p>${report?'报告已汇总本周检查与整改情况。待复核记录单独列出，可继续调整内容。':'3 号泵温度持续偏高，2 号传感器通信中断。建议先核查现场，再决定处置措施。'}</p><div class="file-meta">来源：${report?'检查与整改记录':'设备监测 · 现场巡检记录'} · 示例采集时间 09-13 10:00</div><div class="result-actions"><button class="btn" data-action="result-details">${icon('file')}查看依据</button><button class="btn" data-action="task-draft">${icon('todo')}生成复核待办</button><button class="btn" data-action="export-report">${icon('download')}导出摘要</button></div></div>`;}
function messages(){return `<div class="messages">${(current()?.messages||[]).map((m,i)=>m.role==='user'?`<div class="message user"><div class="user-bubble">${esc(m.text)}${m.attachments?.length?`<div class="file-meta">附件：${m.attachments.map(f=>esc(f)).join('、')}</div>`:''}</div></div>`:`<article class="message assistant"><div class="ai-heading"><span class="logo-mark">${icon('spark')}</span>奇术 AI<small>${esc(m.model||state.settings.model)} · 模拟回复</small></div><div class="ai-content"><p class="${m.status==='running'?'stream-text':''}">${esc(m.text).replace(/\n/g,'<br>')}</p>${m.status?`<small class="stream-status">${{running:'正在生成…',complete:'生成完成',stopped:'已停止生成，保留部分输出',failed:'生成中断，已保留输出；请补充要求后重新发送。'}[m.status]}</small>`:''}${m.kind?assistantResult(m.kind):''}</div><div class="message-actions">${ib('copy','复制回复','copy-message',`data-index="${i}"`)}${ib('refresh','重新生成','retry-message',`data-index="${i}"`)}${ib('thumb',m.liked?'取消赞同':'赞同回复','like-message',`data-index="${i}" aria-pressed="${!!m.liked}" style="${m.liked?'color:#608343;background:#e8efdf':''}"`)}</div></article>`).join('')}${interactionView()}${ui.pending?'<div class="pending" role="status"><i></i><i></i><i></i>正在整理演示资料…</div>':''}</div>`;}
function center(){const chatting=!!current();return `<main class="center"><div class="center-top"><div class="breadcrumb">${icon('chat')}<span>${ui.mode==='overview'?'工作台概览':chatting?esc(current().title):'新会话'}</span></div>${ib('more','会话选项',chatting?'session-menu':'new-options',chatting?`data-id="${current().id}"`:'')}</div><div class="center-scroll" id="center-scroll">${ui.mode==='overview'?overview():chatting?messages():`<div class="welcome"><div class="welcome-symbol">${icon('spark')}</div><div class="eyebrow">YOUR DAY, REIMAGINED WITH AI</div><h1>上午好，王工。<br><span>今天，我们一起完成什么？</span></h1><p>从一个想法，到一次行动。你的 AI 工作伙伴，随时就绪。</p>${composer()}<div class="welcome-tip">${icon('shield')}当前任务仅使用「${esc(ws().name.split(' · ')[0])}」的工作区资料</div></div>`}</div>${chatting&&ui.mode==='chat'?`<div class="chat-composer">${composer()}</div>`:''}<div class="center-footer">内容由 AI 生成，请核实重要信息 <span>·</span> 本地交互演示，未连接业务系统</div></main>`;}
function overview(){return `<div class="overview-title"><div class="eyebrow muted">WORKSPACE AT A GLANCE</div><h1>让每一件事，都有进展。</h1><p>${esc(ws().name)} · 任务与应用概览</p></div><div class="overview-grid">${[['chat','继续对话',`${ws().sessions.length} 个会话保留了工作上下文。`,'chat-mode'],['todo','待办提醒',`${ws().todos.filter(t=>!t.done).length} 项待办等待处理。`,'show-todos'],['calendar','日程安排',`${ws().events.length} 项日程已安排。`,'show-calendar'],['grid','应用能力','在一个入口中使用全部已授权应用。','all-apps']].map(([ic,title,desc,action])=>`<div class="overview-card"><strong>${icon(ic)} ${title}</strong><p>${desc}</p><button class="btn" data-action="${action}">打开${icon('arrow')}</button></div>`).join('')}</div>`;}
function filesMarkup(){return ws().files.map((f,i)=>`<div class="file-row"><span class="file-icon ${i%3===1?'blue':i%3===2?'green':''}">${icon('file')}</span><button class="file-open" data-action="file-preview" data-id="${f.id}"><strong>${esc(f.name)}</strong><small>${esc(f.size)} · ${f.sample?'工作区资料':'本次添加'}</small></button>${ib('trash','删除文件 '+f.name,'delete-file',`data-id="${f.id}"`)}</div>`).join('');}
function workspacePanel(){return `<div class="panel-heading"><h3>当前项目</h3><button class="text-button" data-action="project-new">${icon('plus')}新建</button></div><div class="project-card"><div class="project-top"><span class="project-icon">${icon('folder')}</span><div><strong>${esc(ws().project)}</strong><small>工作区项目 · 仅自己可见</small></div></div><div class="project-status"><span class="dot"></span>${ws().sessions.length} 个会话 · ${ws().files.length} 份资料</div><button data-action="project-detail">查看项目 ${icon('arrow')}</button></div><div class="panel-section"><div class="panel-heading"><h3>${icon('folder')}工作区文件</h3>${ib('plus','添加工作区文件','upload','data-target="workspace"')}</div><p class="panel-desc">与 AI 共享资料，让每次回答更懂你的工作。</p>${filesMarkup()}<button class="drop-area" data-action="upload" data-target="workspace">${icon('upload')}点击或拖拽文件到这里</button></div><div class="assistant-note">${icon('spark')}<span>在对话中描述你的目标，奇术会为你找到合适的应用与资料。</span></div>`;}
function todosPanel(){const pending=ws().todos.filter(t=>!t.done).length;return `<div class="panel-heading"><h3>我的待办</h3><button class="text-button" data-action="todo-new">${icon('plus')}新建</button></div><div class="todo-count">${pending.toString().padStart(2,'0')}</div><p class="panel-desc">项待办等待完成</p>${ws().todos.map(t=>`<div class="todo-item ${t.done?'done':''}"><input type="checkbox" aria-label="完成 ${esc(t.text)}" data-todo="${t.id}" ${t.done?'checked':''}><div class="todo-info"><strong>${esc(t.text)}</strong><small>${esc(t.date||'未设日期')} · ${t.done?'已完成':'待处理'}</small></div>${ib('edit','编辑待办 '+t.text,'todo-edit',`data-id="${t.id}"`)}${ib('trash','删除待办 '+t.text,'todo-delete',`data-id="${t.id}"`)}</div>`).join('')||'<div class="empty">所有事情都已安排妥当。<br>新建一项待办，继续推进。</div>'}<button class="drop-area" data-action="todo-new">${icon('plus')}添加一项待办</button>`;}
function calendarPanel(){const [year,month]=ui.calendar.split('-').map(Number);const offset=(new Date(year,month-1,1).getDay()+6)%7;const days=new Date(year,month,0).getDate();const events=ws().events.filter(e=>e.date===ui.day).sort((a,b)=>a.time.localeCompare(b.time));return `<div class="panel-heading"><h3>我的日程</h3><button class="text-button" data-action="event-new">${icon('plus')}新建</button></div><div class="calendar-head"><span>${year} 年 ${month} 月</span><div>${ib('left','上个月','month-prev')}${ib('next','下个月','month-next')}</div></div><div class="calendar-week">${['一','二','三','四','五','六','日'].map(d=>`<span>${d}</span>`).join('')}${'<span></span>'.repeat(offset)}${Array.from({length:days},(_,i)=>{const date=ui.calendar+'-'+String(i+1).padStart(2,'0');return `<button class="calendar-day ${date===ui.day?'selected':''} ${date===BASE_DATE?'today':''} ${ws().events.some(e=>e.date===date)?'has-event':''}" data-action="select-day" data-date="${date}" aria-label="${date}" aria-pressed="${date===ui.day}">${i+1}</button>`;}).join('')}</div><div class="panel-section"><div class="panel-heading"><h3>${esc(ui.day)} 的安排</h3><button class="text-button" data-action="calendar-today">回到示例日</button></div>${events.length?events.map(e=>`<div class="event-row"><small>${esc(e.time)} · ${esc(e.place||'未设置地点')}</small><strong>${esc(e.title)}</strong><button class="text-button" data-action="event-edit" data-id="${e.id}">编辑</button><button class="text-button" data-action="event-delete" data-id="${e.id}">删除</button></div>`).join(''):'<p class="empty">这一天暂无安排<br>留一点时间，给新的想法。</p>'}<button class="drop-area" data-action="event-new">${icon('plus')}安排一项日程</button></div>`;}
function rightPanel(){return `<aside class="right-panel ${ui.right?'':'hidden'}" aria-label="工作区辅助面板" ${ui.right?'':'inert'}><div class="right-tabs" role="tablist" aria-label="辅助面板">${[['workspace','工作区'],['todos','待办提醒'],['calendar','日程安排']].map(([key,label])=>`<button class="right-tab ${ui.tab===key?'active':''}" role="tab" aria-selected="${ui.tab===key}" aria-controls="right-content" data-action="right-tab" data-tab="${key}">${label}${key==='todos'?`<span class="count">${ws().todos.filter(t=>!t.done).length}</span>`:''}</button>`).join('')}</div><div class="right-content" id="right-content" role="tabpanel" aria-label="${{workspace:'工作区',todos:'待办提醒',calendar:'日程安排'}[ui.tab]}">${ui.tab==='workspace'?workspacePanel():ui.tab==='todos'?todosPanel():calendarPanel()}</div><div class="panel-bottom"><span>${icon('shield')}工作区数据隔离</span><span>仅本机保存</span></div></aside>`;}
function renderApp(){document.body.className=[state.settings.theme==='dark'?'dark':'',state.settings.compact?'compact':''].join(' ');$('#root').innerHTML=`<div class="app"><header class="topbar"><div class="topbar-left">${brand()}<span class="topbar-divider"></span><span class="platform-label">AI 工作台</span>${ib('panel',ui.left?'收起左侧导航':'展开左侧导航','toggle-left',`aria-expanded="${ui.left}"`)}</div><div class="topbar-right"><button class="text-button interaction-entry" data-action="interaction-demo">交互演示</button><span class="topbar-status"><i class="dot"></i>你的 AI 工作伙伴 <span class="tag">演示</span></span>${ib('grid','切换工作台','switch-mode')}${ib('right',ui.right?'收起右侧面板':'展开右侧面板','toggle-right',`aria-expanded="${ui.right}"`)}</div></header><div class="body-layout"><button class="mobile-overlay ${innerWidth<=700&&(ui.left||ui.right)?'active':''}" data-action="dismiss-panels" aria-label="收起导航面板"></button>${sidebar()}${center()}${rightPanel()}</div></div>`;syncPanelDom();applySystemDemo();}
function render(){user?renderApp():renderLogin();}
function scrollChat(){requestAnimationFrame(()=>{const c=$('#center-scroll');if(c)c.scrollTop=c.scrollHeight;});}
function stopPending(){clearTimeout(timer);ui.pending=null;}
function newChat(){stopPending();ws().current=null;ui.draft='';ui.attachments=[];ui.mode='chat';if(innerWidth<=700)ui.left=false;save();renderApp();$('#prompt')?.focus();}
function send(text){if(systemDemo.connection!=='connected'&&systemDemo.connection!=='restored'){toast('连接恢复后才能发送，草稿已保留。');return;}if(systemDemo.mode==='loading'){toast('请等待加载完成。');return;}if(['empty','history'].includes(systemDemo.mode))resetSystemDemo();const message=(text??ui.draft).trim();if(current()?.interaction){toast('请先完成对话中的确认，再发送新任务。');return;}if(ui.pending)return;if(!message&&!ui.attachments.length){toast('先说说你想完成什么，或添加一个文件。');$('#prompt')?.focus();return;}ui.mode='chat';let s=current();if(!s){s={id:uid(),title:message.slice(0,22)||'文件分析',pinned:false,messages:[]};ws().sessions.unshift(s);ws().current=s.id;}s.messages.push({role:'user',text:message||'请帮我分析这些文件。',attachments:ui.attachments.map(f=>f.name)});const hasFiles=ui.attachments.length>0;ui.draft='';ui.attachments=[];save();simulateReply(s,message,hasFiles);}
function simulateReply(s,message,hasFiles=false){const workspaceId=state.workspace;ui.pending=s.id;renderApp();scrollChat();timer=setTimeout(()=>{const report=/报告|周报|总结/.test(message);const text=hasFiles?'附件名称已记录。此原型不会读取文件内容；下面展示资料分析后的交互样式，你可以继续补充任务目标。':/巡检|计划|安排/.test(message)?'我可以先为你整理一份巡检安排。建议优先核查二车间设备状态，再复核待整改记录；执行前可在右侧补充负责人和时间。':report?'已为你准备一份安全生产周报草稿。下面是示例摘要，你可以继续要求调整重点、查看依据或导出。':`收到「${message.slice(0,100)}」。我先为你整理了设备与巡检记录的示例概览，便于继续定位问题、查看依据和安排复核。`;if(state.workspace!==workspaceId)return;s.messages.push({role:'assistant',text,kind:report?'report':'analysis',model:state.settings.model});ui.pending=null;save();renderApp();scrollChat();},1000);}

function workspaceModal(){openModal('选择工作区',`<p class="modal-intro">会话、资料、待办与日程随工作区切换。当前未发送的输入将被清空。</p><div class="modal-list">${Object.entries(state.workspaces).map(([id,w])=>`<button class="choice-row ${state.workspace===id?'selected':''}" data-action="choose-workspace" data-id="${id}">${icon('box')}<span><strong>${esc(w.name)}</strong><small>${w.sessions.length} 个会话 · ${w.files.length} 份资料</small></span>${state.workspace===id?icon('check'):icon('next')}</button>`).join('')}</div><div class="modal-actions"><button class="btn" data-action="workspace-new">${icon('plus')}新建工作区</button></div>`);}
function textForm(title,label,value,form,hidden='',help=''){openModal(title,`<form id="${form}">${hidden}<div class="field"><label for="edit-text">${label}</label><input id="edit-text" name="text" value="${esc(value)}" maxlength="80" required autofocus></div>${help?`<p class="modal-intro">${help}</p>`:''}${buttons('保存')}</form>`);}
function confirmDelete(title,text,action,id){openModal(title,`<p class="modal-intro">${esc(text)}</p><div class="modal-actions"><button class="btn" data-action="close-modal">取消</button><button class="btn danger" data-action="${action}" data-id="${id}">确认删除</button></div>`);}
function sessionMenu(id){const s=ws().sessions.find(s=>s.id===id);if(!s)return;openModal('管理会话',`<p class="modal-intro">${esc(s.title)}</p><div class="modal-list"><button class="choice-row" data-action="pin-session" data-id="${id}">${icon('pin')}<span>${s.pinned?'取消置顶':'置顶会话'}</span></button><button class="choice-row" data-action="rename-session" data-id="${id}">${icon('edit')}<span>重命名</span></button><button class="choice-row" data-action="export-session" data-id="${id}">${icon('download')}<span>导出会话</span></button><button class="choice-row" data-action="delete-session" data-id="${id}">${icon('trash')}<span>归档会话</span></button></div>`);}
function catalog(category){const c=categories[category];if(!c)return;openModal(c.title,`<p class="modal-intro">${c.desc}</p><label class="sr-only" for="catalog-search">搜索${c.title}</label><input class="search-input" id="catalog-search" placeholder="搜索${c.title}…"><div class="catalog">${c.items.map(([name,desc,ic])=>`<article class="catalog-card" data-search="${esc(name+' '+desc)}"><span class="app-icon">${icon(ic)}</span><strong>${name}</strong><p>${desc}</p><button class="btn" data-action="app-detail" data-category="${category}" data-name="${name}">${category==='plugins'?'管理插件':category==='terminals'?'配置连接':'查看详情'}${icon('arrow')}</button></article>`).join('')}</div><p id="catalog-empty" class="empty" hidden>没有找到匹配的内容。</p>`,true);}
function appDetail(category,name){const c=categories[category];const item=c?.items.find(i=>i[0]===name);if(!item)return;const enabled=!!state.enabled[name];const settings=category==='plugins'||category==='terminals';openModal(name,`<p class="modal-intro">${c.title} / ${esc(ws().name)}</p><div class="detail-banner"><h3>${icon(item[2])} ${name}</h3><p>${item[1]}</p></div><dl class="detail-info"><dt>访问范围</dt><dd>当前工作区</dd><dt>运行方式</dt><dd>${category==='terminals'?'模拟消息连接':category==='plugins'?'可选扩展能力':'由奇术在对话中协助调用'}</dd><dt>当前状态</dt><dd>${settings?(enabled?'已启用（本机演示）':'未启用'):'可体验 · 示例数据'}</dd></dl><p class="modal-intro">此页面用于体验交互，不连接真实设备、外部应用或消息服务。</p><div class="modal-actions"><button class="btn" data-action="catalog" data-category="${category}">返回${c.title}</button>${category==='terminals'?`<button class="btn primary" data-action="terminal-config" data-name="${name}">${enabled?'修改连接':'模拟连接'}</button>`:category==='plugins'?`<button class="btn primary" data-action="toggle-plugin" data-name="${name}">${enabled?'停用插件':'启用插件'}</button>`:`<button class="btn primary" data-action="use-app" data-name="${name}" data-category="${category}">在对话中使用${icon('arrow')}</button>`}</div>`);}
function todoForm(id,defaultText=''){const t=ws().todos.find(t=>t.id===id);openModal(t?'编辑待办':'新建待办',`<form id="todo-form"><input type="hidden" name="id" value="${esc(id||'')}"><div class="field"><label for="todo-title">待办内容</label><input id="todo-title" name="title" value="${esc(t?.text||defaultText)}" required maxlength="100" placeholder="例如：复核 3 号泵温度异常"></div><div class="field"><label for="todo-date">完成日期</label><input id="todo-date" name="date" type="date" value="${t?.date||BASE_DATE}" required></div><p class="modal-intro">保存到当前工作区的个人待办，不派发给其他人。</p>${buttons('保存待办')}</form>`);}
function eventForm(id){const e=ws().events.find(e=>e.id===id);openModal(e?'编辑日程':'新建日程',`<form id="event-form"><input type="hidden" name="id" value="${esc(id||'')}"><div class="field"><label for="event-title">日程名称</label><input id="event-title" name="title" value="${esc(e?.title||'')}" required maxlength="80" placeholder="例如：二车间现场巡检"></div><div class="field"><label for="event-date">日期</label><input id="event-date" name="date" type="date" value="${e?.date||ui.day}" required></div><div class="field"><label for="event-time">开始时间</label><input id="event-time" name="time" type="time" value="${e?.time||'14:00'}" required></div><div class="field"><label for="event-place">地点（选填）</label><input id="event-place" name="place" value="${esc(e?.place||'')}" maxlength="80" placeholder="添加地点"></div><p class="modal-intro">仅保存为本机日程，不发送邀请或推送。</p>${buttons('保存日程')}</form>`);}
function settingsModal(){openModal('设置',`<p class="modal-intro">偏好会保存到当前浏览器。</p><div class="settings-row"><div><strong>界面外观</strong><small>选择适合你的工作环境</small></div><select id="setting-theme" aria-label="界面外观"><option value="light" ${state.settings.theme==='light'?'selected':''}>浅色</option><option value="dark" ${state.settings.theme==='dark'?'selected':''}>深色</option></select></div><div class="settings-row"><div><strong>紧凑导航</strong><small>减少会话与入口之间的间距</small></div><input id="setting-compact" class="switch" type="checkbox" aria-label="紧凑导航" ${state.settings.compact?'checked':''}></div><div class="settings-row"><div><strong>按 Enter 发送</strong><small>启用时，Shift + Enter 换行；关闭后使用发送按钮</small></div><input id="setting-enter" class="switch" type="checkbox" aria-label="按 Enter 发送" ${state.settings.enterSend?'checked':''}></div><div class="settings-row"><div><strong>默认模型</strong><small>本原型使用模拟回复，不调用真实模型</small></div><select id="setting-model" aria-label="默认模型">${models.map(m=>`<option ${m===state.settings.model?'selected':''}>${m}</option>`).join('')}</select></div><div class="modal-actions"><button class="btn" data-action="help">原型说明</button><button class="btn primary" data-action="save-settings">保存设置</button></div>`);}
const localFiles=new Map();
function addFiles(files,target){const list=[...files];if(!list.length)return;let rejected=0;for(const f of list){if(f.size>20*1024*1024){rejected++;continue;}const file={id:uid(),name:f.name,size:f.size>1024*1024?(f.size/1024/1024).toFixed(1)+' MB':Math.max(1,Math.round(f.size/1024))+' KB',type:f.name.split('.').pop().toUpperCase(),sample:false};localFiles.set(file.id,f);if(target==='workspace')ws().files.push(file);else ui.attachments.push(file);}save();renderApp();toast(rejected?'已跳过大于 20 MB 的文件，其余文件已添加。':target==='workspace'?'文件已添加到当前工作区。':'附件已添加，可继续描述分析目标。');}
async function previewFile(id){const f=ws().files.find(f=>f.id===id);if(!f)return;let body=`<dl class="detail-info"><dt>文件名</dt><dd>${esc(f.name)}</dd><dt>大小</dt><dd>${esc(f.size)}</dd><dt>工作区</dt><dd>${esc(ws().name)}</dd></dl>`;const raw=localFiles.get(id);if(raw&&/\.(txt|csv|md|json|log)$/i.test(f.name)){body+=`<pre>${esc((await raw.text()).slice(0,12000))}</pre>`;}else body+=`<div class="detail-banner"><p>${f.sample?'这是预置的示例资料入口，可把它添加到对话上下文体验文件分析。':'文件元信息已保存。该格式不提供预览；刷新后需要重新选择原文件才能下载。'}</p></div>`;body+=`<div class="modal-actions"><button class="btn" data-action="download-file" data-id="${id}">${icon('download')}${raw?'下载原文件':'下载示例说明'}</button><button class="btn primary" data-action="reference-file" data-id="${id}">添加到对话</button></div>`;openModal('文件预览',body);}
function download(name,content,type='text/plain;charset=utf-8'){const blob=content instanceof Blob?content:new Blob([content],{type});const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download=name;document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),1000);}
function resultDetails(){openModal('分析依据',`<p class="modal-intro">以下记录用于演示从结论查看证据的流程。</p><div class="detail-banner"><h3>3 号泵 · 温度异常</h3><p>09:48 至 10:00 温度持续偏高，最新示例读数为 86°C。当前数据不足以确定原因，需要现场复核。</p></div><dl class="detail-info"><dt>设备监测</dt><dd>示例采集时间：2026-09-13 10:00<br>轴承温度：86°C；状态：待复核</dd><dt>现场巡检</dt><dd>上一份检查记录未发现可见泄漏。</dd><dt>通信异常</dt><dd>2 号传感器最后通信：09:55，需要检查网络与供电。</dd><dt>资料范围</dt><dd>${esc(ws().name)} · 本机演示资料</dd></dl><div class="modal-actions"><button class="btn" data-action="close-modal">关闭</button><button class="btn primary" data-action="task-draft">创建复核待办</button></div>`);}
function help(){openModal('欢迎体验奇术',`<p class="modal-intro">这是依据 AI 工作台 PRD 制作的登录页与主页交互原型。所有业务结果均为演示。</p><div class="modal-list"><div class="choice-row">${icon('user')}<span><strong>演示登录</strong><small>用户名 admin，密码 Demo@2026。自动登录只保存演示身份，不保存密码。</small></span></div><div class="choice-row">${icon('chat')}<span><strong>用对话开始工作</strong><small>可发送消息、上传附件、切换模型、管理会话。Ctrl + K 新建会话。</small></span></div><div class="choice-row">${icon('folder')}<span><strong>完整体验主页</strong><small>应用入口、工作区、待办和日程均可点击；表单保存至本机浏览器。</small></span></div><div class="choice-row">${icon('info')}<span><strong>原型范围</strong><small>无真实认证、模型推理、消息推送、外部连接或设备控制。附件内容不上传。</small></span></div></div><div class="modal-actions"><button class="btn primary" data-action="close-modal">开始体验</button></div>`);}

document.addEventListener('click',async event=>{
 const b=event.target.closest('[data-action]');if(!b||b.disabled)return;
 const action=b.dataset.action,id=b.dataset.id,name=b.dataset.name,category=b.dataset.category;
 switch(action){
  case 'close-modal':closeModal();break;
  case 'help':help();break;
  case 'fill-demo':$('#username').value='admin';$('#password').value='Demo@2026';$('#login-error').textContent='';$('#username').focus();break;
  case 'toggle-password':{const p=$('#password');p.type=p.type==='password'?'text':'password';const label=p.type==='password'?'显示密码':'隐藏密码';b.innerHTML=icon(p.type==='password'?'eye':'eyeOff');b.setAttribute('aria-label',label);b.title=label;break;}
  case 'password-help':openModal('找回密码',`<p class="modal-intro">正式平台由企业管理员协助重置账号密码。本原型无需找回，可使用下方演示账号。</p><div class="detail-banner"><p>用户名：admin<br>密码：Demo@2026</p></div><div class="modal-actions"><button class="btn primary" data-action="close-modal">我知道了</button></div>`);break;
  case 'toggle-left':ui.left=!ui.left;if(innerWidth<=700&&ui.left)ui.right=false;renderApp();break;
  case 'toggle-right':ui.right=!ui.right;if(innerWidth<=700&&ui.right)ui.left=false;renderApp();break;
  case 'dismiss-panels':ui.left=false;ui.right=false;renderApp();break;
  case 'workspaces':workspaceModal();break;
  case 'choose-workspace':stopPending();state.workspace=id;ui.draft='';ui.attachments=[];ui.mode='chat';if(innerWidth<=700)ui.left=false;save();closeModal();renderApp();toast('已切换到 '+ws().name);break;
  case 'workspace-new':textForm('新建工作区','工作区名称','','workspace-form','','新工作区独立保存会话、待办与日程。');break;
  case 'new-chat':newChat();break;
  case 'select-session':stopPending();ws().current=id;ui.mode='chat';ui.draft='';ui.attachments=[];if(innerWidth<=700)ui.left=false;save();renderApp();scrollChat();break;
  case 'session-menu':sessionMenu(id);break;
  case 'pin-session':{const s=ws().sessions.find(s=>s.id===id);s.pinned=!s.pinned;save();closeModal();renderApp();toast(s.pinned?'会话已置顶。':'已取消置顶。');break;}
  case 'rename-session':textForm('重命名会话','会话名称',ws().sessions.find(s=>s.id===id).title,'rename-form',`<input type="hidden" name="id" value="${id}">`);break;
  case 'delete-session':confirmDelete('删除会话','该会话及其消息将从当前工作区删除，无法恢复。','confirm-delete-session',id);break;
  case 'confirm-delete-session':if(ui.pending===id)stopPending();ws().sessions=ws().sessions.filter(s=>s.id!==id);if(ws().current===id)ws().current=null;save();closeModal();renderApp();toast('会话已删除。');break;
  case 'export-session':{const s=ws().sessions.find(s=>s.id===id);download(s.title+'.txt',s.title+'\n\n'+s.messages.map(m=>(m.role==='user'?'我':'奇术 AI')+'：'+m.text).join('\n\n'));toast('会话已导出。');break;}
  case 'new-options':openModal('会话偏好',`<p class="modal-intro">为新的对话选择你的工作方式。</p><div class="modal-list"><button class="choice-row" data-action="settings">${icon('settings')}<span>模型与输入设置</span>${icon('next')}</button><button class="choice-row" data-action="help">${icon('info')}<span>查看使用说明</span>${icon('next')}</button></div>`);break;
  case 'switch-mode':openModal('切换工作台',`<p class="modal-intro">根据当前任务，选择对话或概览。两种视图共用当前工作区。</p><div class="modal-list"><button class="choice-row ${ui.mode==='chat'?'selected':''}" data-action="choose-mode" data-mode="chat">${icon('chat')}<span><strong>对话工作台</strong><small>通过对话发起任务，按需查看资料与结果</small></span>${icon('next')}</button><button class="choice-row ${ui.mode==='overview'?'selected':''}" data-action="choose-mode" data-mode="overview">${icon('grid')}<span><strong>工作区概览</strong><small>集中查看会话、待办、日程与应用入口</small></span>${icon('next')}</button></div>`);break;
  case 'choose-mode':ui.mode=b.dataset.mode;closeModal();renderApp();break;
  case 'chat-mode':ui.mode='chat';renderApp();break;
  case 'show-todos':ui.right=true;ui.tab='todos';renderApp();break;
  case 'show-calendar':ui.right=true;ui.tab='calendar';renderApp();break;
  case 'all-apps':catalog('apps');break;
  case 'right-tab':ui.tab=b.dataset.tab;renderApp();break;
  case 'thinking':ui.thinking=!ui.thinking;renderApp();$('#prompt')?.focus();toast(ui.thinking?'已启用深度思考演示模式。':'已关闭深度思考演示模式。');break;
  case 'suggestion':send(b.dataset.text);break;
  case 'send':send();break;
  case 'stop':stopPending();current()?.messages.push({role:'assistant',text:'已停止生成。你可以重新描述目标或继续提问。'});save();renderApp();scrollChat();break;
  case 'upload':ui.fileTarget=b.dataset.target;$('#file-input').value='';$('#file-input').click();break;
  case 'remove-attachment':ui.attachments=ui.attachments.filter(f=>f.id!==id);renderApp();break;
  case 'voice':openModal('语音输入',`<p class="modal-intro">原型不访问麦克风。选择一句示例语音，体验转写到输入框后的操作。</p><div class="modal-list">${['帮我看看今天的设备状态','把本周安全检查整理成报告','安排明天下午的车间巡检'].map(t=>`<button class="choice-row" data-action="voice-transcript" data-text="${t}">${icon('mic')}<span>${t}</span>${icon('arrow')}</button>`).join('')}</div>`);break;
  case 'voice-transcript':ui.draft=b.dataset.text;ui.mode='chat';closeModal();renderApp();$('#prompt')?.focus();toast('示例语音已转写，可修改后发送。');break;
  case 'copy-message':{const text=current()?.messages[Number(b.dataset.index)]?.text||'';try{await navigator.clipboard.writeText(text);toast('回复已复制。');}catch{openModal('复制回复',`<div class="field"><label for="copy-text">请选择并复制以下内容</label><textarea id="copy-text" readonly>${esc(text)}</textarea></div>`);$('#copy-text').select();}break;}
  case 'retry-message':{if(ui.pending){toast('请等待当前回复完成，或先停止生成。');break;}const s=current();const prev=s.messages.slice(0,Number(b.dataset.index)).reverse().find(m=>m.role==='user');if(prev)simulateReply(s,prev.text);break;}
  case 'like-message':{const m=current().messages[Number(b.dataset.index)];m.liked=!m.liked;save();renderApp();scrollChat();toast(m.liked?'已记录你的赞同。':'已取消赞同。');break;}
  case 'result-details':resultDetails();break;
  case 'task-draft':todoForm(null,'现场复核 3 号泵温度异常');break;
  case 'export-report':download('奇术-安全生产摘要.txt','奇术 · 安全生产摘要（演示）\n工作区：'+ws().name+'\n示例时间：2026-09-13 10:00\n\n设备总数：128 台，正常运行：126 台。\n待关注：3 号泵温度偏高；2 号传感器通信中断。\n建议：现场复核后决定处置措施。\n\n本内容为原型示例，不代表实际生产情况。\n');toast('示例摘要已导出。');break;
  case 'catalog':catalog(category);break;
  case 'app-detail':appDetail(category,name);break;
  case 'use-app':if(category==='apps'){state.recent=[name,...state.recent.filter(n=>n!==name)].slice(0,4);save();}closeModal();newChat();ui.draft='请使用'+name+'，帮我';renderApp();$('#prompt')?.focus();toast('已选择'+name+'，补充你的目标即可开始。');break;
  case 'toggle-plugin':state.enabled[name]=!state.enabled[name];save();appDetail('plugins',name);toast(state.enabled[name]?'插件已在原型中启用。':'插件已停用。');break;
  case 'terminal-config':openModal('连接'+name,`<form id="terminal-form"><input type="hidden" name="name" value="${name}"><p class="modal-intro">仅模拟连接流程。无需真实凭据，不会向外部服务发送消息。</p><div class="field"><label for="terminal-label">连接名称</label><input id="terminal-label" name="label" value="${esc(state.enabled[name]?.label||'工厂安全协作群')}" maxlength="60" required></div><div class="field"><label for="terminal-scope">接收内容</label><select id="terminal-scope" name="scope"><option>待办与日程提醒</option><option>仅异常事件</option><option>任务完成通知</option></select></div>${buttons('保存模拟连接')}</form>${state.enabled[name]?`<div class="modal-actions"><button class="btn danger" data-action="disconnect-terminal" data-name="${name}">断开模拟连接</button></div>`:''}`);break;
  case 'disconnect-terminal':delete state.enabled[name];save();appDetail('terminals',name);toast('模拟连接已断开。');break;
  case 'project-new':textForm('新建当前项目','项目名称','','project-form','','当前工作区一次展示一个项目。保存后更新当前项目名称，已有文件和会话保留在工作区。');break;
  case 'project-detail':openModal(ws().project,`<p class="modal-intro">${esc(ws().name)} / 当前项目</p><div class="detail-banner"><h3>${ws().sessions.length} 个会话，${ws().files.length} 份资料</h3><p>围绕同一工作目标管理资料。所有内容在当前工作区中保留。</p></div><div class="modal-list">${ws().sessions.slice(0,4).map(s=>`<button class="choice-row" data-action="project-session" data-id="${s.id}">${icon('chat')}<span>${esc(s.title)}</span>${icon('next')}</button>`).join('')}</div><div class="modal-actions"><button class="btn" data-action="project-rename">重命名项目</button><button class="btn primary" data-action="project-chat">发起新会话</button></div>`);break;
  case 'project-session':closeModal();stopPending();ws().current=id;ui.mode='chat';ui.draft='';ui.attachments=[];save();renderApp();scrollChat();break;
  case 'project-rename':textForm('重命名项目','项目名称',ws().project,'project-form');break;
  case 'project-chat':closeModal();newChat();break;
  case 'file-preview':await previewFile(id);break;
  case 'delete-file':confirmDelete('删除工作区文件','删除此资料入口，不会删除你电脑上的原始文件。','confirm-delete-file',id);break;
  case 'confirm-delete-file':ws().files=ws().files.filter(f=>f.id!==id);localFiles.delete(id);save();closeModal();renderApp();toast('文件已从工作区移除。');break;
  case 'reference-file':{const f=ws().files.find(f=>f.id===id);if(!ui.attachments.some(a=>a.id===id))ui.attachments.push(f);ui.mode='chat';closeModal();renderApp();$('#prompt')?.focus();toast('资料已添加到对话附件。');break;}
  case 'download-file':{const f=ws().files.find(f=>f.id===id);download(localFiles.has(id)?f.name:f.name+'-示例说明.txt',localFiles.get(id)||`示例资料：${f.name}\n此条目用于交互演示，不包含实际文档正文。\n工作区：${ws().name}\n`);toast('文件已准备下载。');break;}
  case 'todo-new':todoForm();break;
  case 'todo-edit':todoForm(id);break;
  case 'todo-delete':confirmDelete('删除待办','这条待办将从当前工作区删除。','confirm-delete-todo',id);break;
  case 'confirm-delete-todo':ws().todos=ws().todos.filter(t=>t.id!==id);save();closeModal();renderApp();toast('待办已删除。');break;
  case 'event-new':eventForm();break;
  case 'event-edit':eventForm(id);break;
  case 'event-delete':confirmDelete('删除日程','这项日程将从当前工作区删除。','confirm-delete-event',id);break;
  case 'confirm-delete-event':ws().events=ws().events.filter(e=>e.id!==id);save();closeModal();renderApp();toast('日程已删除。');break;
  case 'month-prev':case 'month-next':{const [y,m]=ui.calendar.split('-').map(Number);const d=new Date(y,m-1+(action==='month-next'?1:-1),1);ui.calendar=d.getFullYear()+'-'+String(d.getMonth()+1).padStart(2,'0');ui.day=ui.calendar+'-01';renderApp();break;}
  case 'select-day':ui.day=b.dataset.date;renderApp();break;
  case 'calendar-today':ui.calendar=BASE_DATE.slice(0,7);ui.day=BASE_DATE;renderApp();break;
  case 'profile':openModal('个人账号',`<div class="detail-banner"><h3><span class="avatar">王</span> 王工</h3><p>安全管理员 · 演示账号 admin</p></div><dl class="detail-info"><dt>当前工作区</dt><dd>${esc(ws().name)}</dd><dt>登录状态</dt><dd>本机演示身份${state.rememberUser?' · 已开启自动登录':''}</dd></dl><div class="modal-actions"><button class="btn" data-action="settings">账号偏好</button><button class="btn danger" data-action="logout">${icon('logout')}退出登录</button></div>`);break;
  case 'settings':settingsModal();break;
  case 'save-settings':state.settings={theme:$('#setting-theme').value,compact:$('#setting-compact').checked,enterSend:$('#setting-enter').checked,model:$('#setting-model').value};save();closeModal();renderApp();toast('设置已保存。');break;
  case 'logout':cancelFirstSubmission();rememberDraft();user=null;state.rememberUser=null;try{sessionStorage.removeItem('yuvi-user');}catch{}save();ui.draft='';ui.attachments=[];closeModal();renderLogin();toast('已退出登录，本机工作资料已保留。');break;
 }
});

document.addEventListener('submit',event=>{
 const form=event.target;const formId=form.getAttribute('id');event.preventDefault();const data=new FormData(form);
 if(formId==='login-form'){
  const username=String(data.get('username')||'').trim(),password=String(data.get('password')||'');
  $('#username').removeAttribute('aria-invalid');$('#password').removeAttribute('aria-invalid');
  if(!username||!password){$('#login-error').textContent='请输入用户名和密码。';const field=!username?$('#username'):$('#password');field.setAttribute('aria-invalid','true');field.focus();return;}
  if(username!=='admin'||password!=='Demo@2026'){$('#login-error').textContent='演示账号或密码不正确，请使用下方演示账号。';$('#password').setAttribute('aria-invalid','true');return;}
  user={name:'王工',username:'admin'};state.rememberUser=$('#remember').checked?user:null;try{sessionStorage.setItem('yuvi-user',JSON.stringify(user));}catch{}save();renderApp();toast('欢迎回来，王工。');return;
 }
 if(!form.checkValidity()){form.reportValidity();return;}
 const requiredText=String(data.get('text')||data.get('title')||data.get('label')||'').trim();
 if(['workspace-form','rename-form','project-form','todo-form','event-form','terminal-form'].includes(formId)&&!requiredText){toast('内容不能只包含空格。');return;}
 switch(formId){
  case 'workspace-form':{const id=uid();const w=seedWorkspace(requiredText);w.sessions=[];w.files=[];w.todos=[];w.events=[];w.project='我的新项目';state.workspaces[id]=w;state.workspace=id;stopPending();ui.draft='';ui.attachments=[];break;}
  case 'rename-form':ws().sessions.find(s=>s.id===data.get('id')).title=requiredText;break;
  case 'project-form':ws().project=requiredText;break;
  case 'todo-form':{const id=String(data.get('id'));const t=ws().todos.find(t=>t.id===id);if(t){t.text=requiredText;t.date=String(data.get('date'));}else ws().todos.unshift({id:uid(),text:requiredText,date:String(data.get('date')),done:false});ui.tab='todos';ui.right=true;break;}
  case 'event-form':{const id=String(data.get('id'));const value={id:id||uid(),title:requiredText,date:String(data.get('date')),time:String(data.get('time')),place:String(data.get('place')).trim()};const i=ws().events.findIndex(e=>e.id===id);if(i>=0)ws().events[i]=value;else ws().events.push(value);ui.day=value.date;ui.calendar=value.date.slice(0,7);ui.tab='calendar';ui.right=true;break;}
  case 'terminal-form':state.enabled[String(data.get('name'))]={label:requiredText,scope:String(data.get('scope'))};save();appDetail('terminals',String(data.get('name')));toast('模拟连接已保存，未连接外部服务。');return;
  default:return;
 }
 save();closeModal();renderApp();toast('已保存到当前工作区。');
});
document.addEventListener('input',event=>{
 if(event.target.id==='prompt')ui.draft=event.target.value;
 if(event.target.id==='catalog-search'){let visible=0;$$('.catalog-card').forEach(card=>{const match=card.dataset.search.toLowerCase().includes(event.target.value.trim().toLowerCase());card.hidden=!match;card.style.display=match?'':'none';if(match)visible++;});$('#catalog-empty').hidden=visible>0;}
});
function $$(q){return [...document.querySelectorAll(q)];}
document.addEventListener('change',event=>{
 if(event.target.id==='model'){state.settings.model=event.target.value;save();toast('已切换至 '+state.settings.model+'（演示）。');}
 if(event.target.dataset.todo){ws().todos.find(t=>t.id===event.target.dataset.todo).done=event.target.checked;save();renderApp();}
 if(event.target.id==='file-input')addFiles(event.target.files,ui.fileTarget);
});
document.addEventListener('keydown',event=>{
 if(event.isComposing)return;
 if(event.key==='Escape'&&!$('#modal').open&&innerWidth<=960&&(ui.right||(innerWidth<=700&&ui.left))){const key=ui.right?'right':'left';ui.right=false;if(innerWidth<=700)ui.left=false;syncPanelDom();$(`[data-action="toggle-${key}"]`)?.focus();return;}
 if(user&&(event.ctrlKey||event.metaKey)&&event.key.toLowerCase()==='k'){event.preventDefault();if($('#modal').open)closeModal();newChat();}
 if(event.target.id==='prompt'&&event.key==='Enter'&&!event.shiftKey&&state.settings.enterSend){event.preventDefault();send();}
 if(event.target.getAttribute('role')==='tab'&&['ArrowLeft','ArrowRight'].includes(event.key)){event.preventDefault();const keys=['workspace','todos','calendar'];ui.tab=keys[(keys.indexOf(ui.tab)+(event.key==='ArrowRight'?1:2))%3];renderApp();$(`[data-tab="${ui.tab}"]`)?.focus();}
});
document.addEventListener('dragover',event=>{const area=event.target.closest('.drop-area,.composer');if(area){event.preventDefault();area.classList.add('dragging');}});
document.addEventListener('dragleave',event=>event.target.closest('.drop-area,.composer')?.classList.remove('dragging'));
document.addEventListener('drop',event=>{const area=event.target.closest('.drop-area,.composer');if(area){event.preventDefault();area.classList.remove('dragging');addFiles(event.dataTransfer.files,area.classList.contains('composer')?'chat':'workspace');}});
render();
