#!/usr/bin/env python3
"""Offline workbench smoke/regression tests; requires Playwright + Chromium.

--mode content injects the already generated bytes into a blank page. It does NOT
verify file:// opening. Storage success tests use an explicitly labeled mock in
this mode; natural storage failure is tested without a mock. No browser policy
is changed. --mode file performs native file navigation where policy permits.
"""
from __future__ import annotations
import argparse
from datetime import datetime, timezone
import json
from pathlib import Path
import re
import traceback
import tempfile
import zipfile
from playwright.sync_api import sync_playwright
from render_prd import read_markdown, render_html, extract_html_state

ROOT=Path(__file__).resolve().parents[1]


def main():
    ap=argparse.ArgumentParser(description=__doc__)
    ap.add_argument('--chromium', default=None)
    ap.add_argument('--mode', choices=['content','file'], default='file')
    ap.add_argument('--out-dir', type=Path, default=ROOT.parent/'test-results/runtime')
    args=ap.parse_args(); args.out_dir.mkdir(parents=True,exist_ok=True)
    html_path=args.out_dir.resolve()/'device-demo.prd.html'
    source=(ROOT/'examples/device-demo-source.md').read_text(encoding='utf-8')
    document=render_html(read_markdown(source,doc_id='synthetic.device',version='demo'),(ROOT/'assets/offline-shell.html').read_text(encoding='utf-8'))
    html_path.write_text(document,encoding='utf-8',newline='\n')
    original=extract_html_state(document)
    report={'startedAt':datetime.now(timezone.utc).isoformat(),'mode':args.mode,
            'cases':[],'limitations':[]}
    console_errors=[]; page_errors=[]; requests=[]
    with tempfile.TemporaryDirectory(prefix='prd-browser-') as navigation_dir, sync_playwright() as pw:
        browser=pw.chromium.launch(headless=True,executable_path=args.chromium,args=['--no-sandbox'])
        report['browser']='Chromium '+browser.version
        context=browser.new_context(viewport={'width':1440,'height':1100},accept_downloads=True)
        context.set_offline(True)
        context.on('request',lambda req: requests.append(req.url) if req.url.startswith(('http:','https:','ws:','wss:')) else None)
        def page_new(content=document,storage=None,viewport=None):
            p=context.new_page()
            if viewport:p.set_viewport_size(viewport)
            p.on('pageerror',lambda e:page_errors.append(str(e)))
            p.on('console',lambda e:console_errors.append(e.text) if e.type=='error' else None)
            if storage is not None:
                p.evaluate('''initial => {
                  const store = new Map(Object.entries(initial));
                  const api={getItem:k=>store.has(k)?store.get(k):null,setItem:(k,v)=>store.set(k,String(v)),removeItem:k=>store.delete(k),get length(){return store.size;},key:i=>Array.from(store.keys())[i]??null};
                  Object.defineProperty(window,'localStorage',{configurable:true,value:api});
                  window.__testStorageDump=()=>Object.fromEntries(store);
                }''',storage)
            if args.mode=='file' and storage is None:
                target=html_path if content==document else Path(navigation_dir)/('page-'+str(len(context.pages))+'.html')
                if target!=html_path:target.write_text(content,encoding='utf-8')
                p.goto(target.resolve().as_uri())
            else:
                p.set_content(content,wait_until='domcontentloaded')
            p.wait_for_selector('.section',timeout=5000)
            wait_diagrams(p)
            return p
        def wait_diagrams(p):
            p.wait_for_function("() => document.querySelectorAll('.diagram[data-diagram-state=pending]').length === 0",timeout=20000)
        def case(name,fn,details=''):
            try:
                fn(); report['cases'].append({'name':name,'status':'通过','details':details})
            except Exception as exc:
                report['cases'].append({'name':name,'status':'失败','details':str(exc),'traceback':traceback.format_exc()})
                print('FAIL',name,str(exc))
        def require(test,msg='断言失败'):
            if not test:raise AssertionError(msg)
        def get_md(p):
            p.locator('#editBtn').click()
            return p.locator('#source').input_value()
        def download(p,button,name):
            with p.expect_download(timeout=10000) as dl:p.locator(button).click()
            path=args.out_dir/name;dl.value.save_as(path);return path
        def accept(dialog):dialog.accept()
        try:
            page=page_new()
        except Exception as exc:
            report['cases'].append({'name':'初始化文档','status':'阻断','details':str(exc)})
            (args.out_dir/'browser-report.json').write_text(json.dumps(report,ensure_ascii=False,indent=2),encoding='utf-8')
            browser.close();return 1
        page.on('dialog',accept)
        case('离线内容渲染：15 个章节、表格、代码与两张 Mermaid SVG',lambda:require(page.locator('.section').count()==15 and page.locator('table').count()>8 and page.locator('pre').count()>=4 and page.locator('.diagram-view svg').count()==2))
        def explicit_test_content():
            requirements=page.locator('.section').filter(has=page.locator('.sectionbar h2',has_text='二、用户故事'))
            testing=page.locator('.section').filter(has=page.locator('.sectionbar h2',has_text='九、测试用例'))
            acceptance=page.locator('.section').filter(has=page.locator('.sectionbar h2',has_text='十、逐项验收'))
            require(requirements.locator('table').nth(2).locator('tbody tr').count()==20)
            require(testing.locator('h4').count()==20)
            require(acceptance.locator('table').count()==2)
            for table in acceptance.locator('table').all():require(table.locator('tbody tr').count()==20)
            require('def generate(' in testing.locator('pre').all_text_contents()[1])
        case('20 条用例与 20 项验收均以表格/详情呈现，完整数据脚本可见',explicit_test_content)
        page.screenshot(path=str(args.out_dir/'desktop.png'))
        page.locator('.diagram').first.screenshot(path=str(args.out_dir/'mermaid-overview.png'))
        page.locator('.diagram').nth(1).screenshot(path=str(args.out_dir/'mermaid-state.png'))
        def search_test():
            page.locator('#search').fill('synthetic-demo-only')
            require(page.locator('.section:visible').count()==1)
            page.locator('#search').fill('')
            require(page.locator('.section:visible').count()==15)
        case('全文搜索与清空恢复',search_test)
        def section_edit():
            page.locator('button[data-edit]').nth(2).click()
            val=page.locator('#sectionSource').input_value()
            page.locator('#sectionSource').fill(val+'\n离线章节编辑验证：中文与 😀。\n')
            page.locator('#applyEditBtn').click()
            require('离线章节编辑验证' in get_md(page))
            page.locator('#readBtn').click()
        case('章节编辑回写唯一正文',section_edit)
        def escape_cancel():
            before=get_md(page);page.locator('#readBtn').click()
            page.locator('button[data-edit]').nth(2).click()
            page.locator('#sectionSource').fill('不会被保存的内容')
            page.keyboard.press('Escape')
            require(not page.locator('#editDialog').is_visible())
            require(get_md(page)==before)
        case('Esc 取消章节编辑且不污染正文',escape_cancel)
        def source_edit():
            before=get_md(page);page.locator('#source').fill(before.replace('"演示设备"','"离线修改后的设备"'))
            page.wait_for_timeout(350)
            require('离线修改后的设备' in page.locator('#article').inner_text())
            page.locator('#readBtn').click()
        case('完整源码编辑与实时预览',source_edit)
        def checkbox():
            page.locator('input[data-task-line]').first.check()
            require('- [x] 收集权限边界' in get_md(page))
            require('不代表测试执行' in page.locator('#toast').inner_text())
            page.locator('#readBtn').click()
        case('任务勾选写回 MD，不冒充验收',checkbox)
        def review():
            page.locator('#reviewBtn').click();page.locator('#reviewAuthor').fill('自动化合成测试')
            page.locator('#reviewRef').fill('BR-02')
            page.locator('#reviewText').fill('合成批注：确认版本冲突。<script>window.__pwned=1</script>')
            page.locator('#addReviewBtn').click()
            require('## 文档评审记录' in get_md(page))
            require('合成批注' in page.locator('#source').input_value())
            require(page.evaluate('window.__pwned === undefined'))
        case('章节批注入正文并安全显示',review)
        current=get_md(page)
        exported={}
        def md_export():
            path=download(page,'#exportMdBtn','roundtrip.prd.md');value=read_markdown(path.read_text(encoding='utf-8'))
            require(value['markdown']==current);exported['state']=value
        case('MD 实际下载与逐字往返一致',md_export)
        def html_export():
            path=download(page,'#exportHtmlBtn','roundtrip.prd.html');value=extract_html_state(path.read_text(encoding='utf-8'))
            require(value==exported['state']);p=page_new(path.read_text(encoding='utf-8'));require('合成批注' in p.locator('#article').inner_text());require(get_md(p)==current);require(p.locator('.diagram-view svg').count()==2);p.close()
        case('HTML 实际下载、重新打开后正文与图形保留',html_export,'file 模式将导出字节写为本地 HTML 并原生导航；content 模式仅注入。')
        def zip_export():
            path=download(page,'#exportBundleBtn','roundtrip.zip')
            with zipfile.ZipFile(path) as z:
                require(z.testzip() is None);require(len(z.namelist())==2)
                md=read_markdown(z.read(next(n for n in z.namelist() if n.endswith('.md'))).decode())
                ht=extract_html_state(z.read(next(n for n in z.namelist() if n.endswith('.html'))).decode())
                require(md==ht==exported['state'])
        case('双格式 ZIP 可解压、CRC 正确、同一快照',zip_export)
        def keyboard_save():
            with page.expect_download() as dl:page.keyboard.press('Control+s')
            path=args.out_dir/'keyboard.zip';dl.value.save_as(path);require(zipfile.is_zipfile(path))
        case('Ctrl+S 导出双格式包',keyboard_save)
        def import_md():
            page.locator('#fileInput').set_input_files(str(args.out_dir/'roundtrip.prd.md'))
            page.wait_for_timeout(200);require(get_md(page)==current)
        case('导出 MD 再导入，不丢失批注和正文',import_md)
        def invalid_import():
            before=get_md(page)
            page.locator('#fileInput').set_input_files({'name':'bad.json','mimeType':'application/json','buffer':b'{"schemaVersion":999}'})
            page.wait_for_timeout(150);require(get_md(page)==before);require('未导入' in page.locator('#toast').inner_text())
        case('非法快照导入保留原文',invalid_import)
        def cancel_import():
            before=get_md(page);page.remove_listener('dialog',accept)
            page.once('dialog',lambda d:d.dismiss())
            page.locator('#fileInput').set_input_files({'name':'other.md','mimeType':'text/markdown','buffer':'# 不应导入\n'.encode()})
            page.wait_for_timeout(150);require(get_md(page)==before);page.on('dialog',accept)
        case('取消导入不覆盖当前内容',cancel_import)
        def storage_unavailable():
            before=get_md(page);page.locator('#cacheOpt').click();page.wait_for_timeout(150)
            require(not page.locator('#cacheOpt').is_checked());require('不可用' in page.locator('#saveStatus').inner_text());require(get_md(page)==before)
            download(page,'#exportMdBtn','cache-fallback.prd.md')
        if args.mode=='content':case('自然缓存不可用时仍可编辑与导出',storage_unavailable,'about:blank 的自然 SecurityError；未模拟失败。')
        def storage_simulation():
            p=page_new(storage={});p.on('dialog',accept);p.locator('#cacheOpt').check()
            before=get_md(p);p.locator('#source').fill(before+'\n模拟缓存恢复验证。\n');p.wait_for_timeout(350)
            values=p.evaluate('window.__testStorageDump()');require(len(values)==1)
            expected=get_md(p);q=page_new(storage=values);q.on('dialog',accept)
            require(q.locator('#recovery').is_visible());q.locator('#restoreBtn').click();require(get_md(q)==expected)
            key=next(iter(values));q.evaluate('(key)=>window.dispatchEvent(new StorageEvent("storage",{key,newValue:"other-writer"}))',key)
            require(not q.locator('#cacheOpt').is_checked());require('另一页面' in q.locator('#saveStatus').inner_text());require(get_md(q)==expected)
            q.close();p.close()
        case('草稿恢复与跨标签冲突保护（存储模拟）',storage_simulation,'使用标记的 Map 存储桩及合成 storage 事件，不声称真实 file:// 持久化验证。')
        def malicious():
            attack='# 安全合成测试\n\n## 输入\n\n<script>window.__pwned=1</script>\n<img src="https://invalid.example/pixel" onerror="window.__pwned=1">\n\n[坏链接](javascript:alert(1))\n\n![追踪图](https://invalid.example/pixel)\n\n```json\n{"x":"</script><script>window.__pwned=1</script>","pipe":"a|b"}\n```\n'
            state=read_markdown(attack,doc_id='test.attack',version='</script><script>x</script>')
            h=render_html(state,(ROOT/'assets/offline-shell.html').read_text(encoding='utf-8'));p=page_new(h)
            require(p.evaluate('window.__pwned === undefined'))
            require(p.locator('#article script,#article iframe,#article img,#article [onerror]').count()==0)
            require(p.locator('a[href^="javascript:"]').count()==0)
            require(get_md(p)==attack)
            path=download(p,'#exportHtmlBtn','attack-roundtrip.html');require(extract_html_state(path.read_text(encoding='utf-8'))['markdown']==attack)
            p.close()
        case('恶意 HTML、数据结束标签、脚本链接与追踪图片',malicious)
        def diagram_edits():
            p=page_new();p.on('dialog',accept)
            before=get_md(p)
            changed=before.replace('设备管理员]','编辑后的管理员]')
            p.locator('#source').fill(changed);p.wait_for_timeout(300);wait_diagrams(p)
            require('编辑后的管理员' in p.locator('.diagram-view').first.inner_text())
            p.locator('#readBtn').click();p.locator('button[data-edit]').nth(1).click()
            text=p.locator('#sectionSource').input_value().replace('编辑后的管理员','章节修改后的管理员')
            p.locator('#sectionSource').fill(text);p.locator('#applyEditBtn').click();wait_diagrams(p)
            require('章节修改后的管理员' in p.locator('.diagram-view').first.inner_text())
            path=download(p,'#exportHtmlBtn','diagram-edited.html');q=page_new(path.read_text(encoding='utf-8'))
            require('章节修改后的管理员' in q.locator('.diagram-view').first.inner_text())
            p.locator('#fileInput').set_input_files({'name':'diagram.md','mimeType':'text/markdown','buffer':'# 导入图\n\n```mermaid\nflowchart LR\n A[导入成功] --> B[保留图形]\n```\n'.encode()})
            p.wait_for_function("() => document.querySelector('#source').value.includes('导入成功')");wait_diagrams(p)
            require('导入成功' in p.locator('.diagram-view').inner_text());q.close();p.close()
        case('Mermaid 全文/章节编辑、导出重开与导入重绘',diagram_edits)
        def diagram_race():
            p=page_new();get_md(p)
            p.evaluate('''() => {
              const original=mermaid.render;
              mermaid.render=async(...args)=>{await new Promise(resolve=>setTimeout(resolve,350));return original(...args);};
            }''')
            p.locator('#source').fill('# 竞态\n\n```mermaid\nflowchart LR\n A[旧修订] --> B\n```\n');p.wait_for_timeout(280)
            p.locator('#source').fill('# 竞态\n\n```mermaid\nflowchart LR\n A[最新修订] --> B\n```\n');p.wait_for_timeout(280);wait_diagrams(p)
            require(p.locator('.diagram-view svg').count()==1)
            require('最新修订' in p.locator('.diagram-view').inner_text() and '旧修订' not in p.locator('.diagram-view').inner_text())
            require(p.locator('.diagram-stage').count()==0);p.close()
        case('Mermaid 慢渲染与连续编辑不回写旧图',diagram_race,'人为延迟图形渲染，验证异步修订竞争。')
        def diagram_errors():
            samples=['flowchart LR\n A[broken', '%%{init: {"securityLevel":"loose"}}%%\nflowchart LR\n A-->B',
                     'flowchart LR\n A-->B\n click A "https://invalid.example/link"',
                     'flowchart LR\n A@{ img: "https://invalid.example/pixel" }',
                     'flowchart LR\n A-->B\n classDef bad fill:url(https://invalid.example/style)',
                     'flowchart LR\n A['+'a'*50001+']',
                     'flowchart LR\n A["<img src=https://invalid.example/pixel onerror=alert(1)>"] --> B',
                     'stateDiagram-v2\n [*] --> 完成']
            md='# 图形错误隔离\n\n'+'\n\n'.join('```mermaid\n'+s+'\n```' for s in samples)+'\n'
            h=render_html(read_markdown(md,doc_id='test.diagrams'),(ROOT/'assets/offline-shell.html').read_text(encoding='utf-8'))
            p=page_new(h)
            require(p.locator('.diagram[data-diagram-state=error]').count()==6,p.locator('.diagram-status').all_text_contents())
            require(p.locator('.diagram-view svg').count()==2)
            require(p.locator('.diagram-error details[open]').count()==6)
            require(p.locator('.diagram-view script,.diagram-view image,.diagram-view foreignObject,.diagram-view [onerror],.diagram-view [href]').count()==0)
            require(get_md(p)==md)
            repaired=md.replace('A[broken','A[repaired]');p.locator('#source').fill(repaired);p.wait_for_timeout(300);wait_diagrams(p)
            require(p.locator('.diagram-view svg').count()==3)
            require('repaired' in p.locator('.diagram-view').first.inner_text());p.close()
        case('Mermaid 错误、配置/链接、超限与 HTML 输入局部处理并可修复',diagram_errors)
        def responsive():
            p=page_new(viewport={'width':390,'height':844})
            require(p.evaluate('document.documentElement.scrollWidth <= innerWidth'))
            require(p.locator('.diagram-view svg').count()==2)
            p.locator('.diagram-controls button').nth(1).click()
            require(p.evaluate('document.documentElement.scrollWidth <= innerWidth'))
            p.locator('#menuBtn').click();require(p.locator('#sidebar').is_visible())
            p.keyboard.press('Escape');require(not p.locator('#sidebar').is_visible())
            p.screenshot(path=str(args.out_dir/'mobile.png'));p.close()
        case('390px 移动布局无页面横向溢出、目录开关',responsive)
        def print_style():
            p=page_new();p.locator('#search').fill('synthetic-demo-only');p.emulate_media(media='print')
            require(not p.locator('.topbar').is_visible());require(p.locator('.section:visible').count()==15)
            require(p.locator('.diagram-view svg:visible').count()==2)
            require(p.locator('.diagram-controls:visible').count()==0)
            p.screenshot(path=str(args.out_dir/'print-style.png'));p.close()
        case('打印样式隐藏控件并恢复全文',print_style,'仅浏览器 print 媒体样式，不是实际打印机/PDF 验收。')
        case('无隐式网络请求',lambda:require(len(requests)==0,str(requests)))
        case('无未处理脚本或控制台错误',lambda:require(not page_errors and not console_errors,str(page_errors+console_errors)))
        report['implicitNetworkRequests']=requests;report['pageErrors']=page_errors;report['consoleErrors']=console_errors
        report['limitations']=[
            'content 模式不覆盖 file:// 启动；file 模式对原始页、导出页与合成输入进行原生本地导航，存储桩用例仍采用内容注入。',
            '仅上述 Chromium 版本与指定视口；未测试 Safari、Firefox、真实移动设备、系统下载策略或辅助阅读器。',
            '缓存成功/恢复及跨标签竞争使用明确标注的存储桩；真实 file:// 缓存持久化未验证。',
            '未测试 up-sl-back 业务程序、数据库、性能或真实业务验收；未测试所有可能的 Markdown 语法。']
        browser.close()
    report['finishedAt']=datetime.now(timezone.utc).isoformat()
    report['summary']={s:sum(c['status']==s for c in report['cases']) for s in ['通过','失败','阻断']}
    (args.out_dir/'browser-report.json').write_text(json.dumps(report,ensure_ascii=False,indent=2),encoding='utf-8')
    print(json.dumps(report['summary'],ensure_ascii=False))
    return 1 if report['summary']['失败'] or report['summary']['阻断'] else 0


if __name__=='__main__':
    raise SystemExit(main())
